# ref: https://hub.docker.com/r/itzg/minecraft-server/
image: itzg/minecraft-server
imageTag: latest

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 3Gi
    cpu: 1
  limits:
    memory: 7Gi
    cpu: 2

nodeSelector: {}

tolerations: []

affinity: {}

# Most of these map to environment variables. See Minecraft for details:
# https://hub.docker.com/r/itzg/minecraft-server/
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 15
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 5

minecraftServer:
  serviceAnnotations: {}
  serviceType: LoadBalancer
  loadBalancerIP: 34.89.229.103
  # loadBalancerSourceRanges: []
  ## Set the externalTrafficPolicy in the Service to either Cluster or Local
  # externalTrafficPolicy: Cluster
  externalIPs:

  ## Additional minecraft container environment variables
  env:
    EULA: "TRUE"
    TYPE: "PAPER"
    VERSION: "LATEST"
    SEED: "fshhu"
  # Builder: https://mctools.org/motd-creator?text=+++++++++%267The+Inofficial%26r+%26b%26lHHU%26r+%267Anarchy+Server%26r%0D%0A+%267Hosted+on%26r+%269%26lG%26r%26c%26lC%26r%26e%26lP%26r+%267by%26r+%26dPaul1365972%26r%267%2C+powered+via+%269%26lK8s%26r
    MOTD: "\\\\u0020\\\\u0020\\\\u0020\\\\u0020\\\\u0020\\\\u0020\\\\u0020\\\\u0020\\\\u0020\\\\u00A77The\\\\u0020Inofficial\\\\u00A7r\\\\u0020\\\\u00A7b\\\\u00A7lHHU\\\\u00A7r\\\\u0020\\\\u00A77Anarchy\\\\u0020Server\\\\u00A7r\\\\u00A7r\\\\n\\\\u0020\\\\u00A77Hosted\\\\u0020on\\\\u00A7r\\\\u0020\\\\u00A79\\\\u00A7lG\\\\u00A7r\\\\u00A7c\\\\u00A7lC\\\\u00A7r\\\\u00A7e\\\\u00A7lP\\\\u00A7r\\\\u0020\\\\u00A77by\\\\u00A7r\\\\u0020\\\\u00A7dPaul1365972\\\\u00A7r\\\\u00A77,\\\\u0020powered\\\\u0020via\\\\u0020\\\\u00A79\\\\u00A7lK8s\\\\u00A7r"
  # TODO Copyright eeeh?
    ICON: "https://raw.githubusercontent.com/Paul1365972/fshhu-server/master/icons/hhu-logo.png"
    DIFFICULTY: "hard"
    SPAWN_PROTECTION: "0"
    VIEW_DISTANCE: "12"
    MAX_PLAYERS: "50"
    MAX_TICK_TIME: "-1"
    OPS: "Paul1365972"
    OVERRIDE_SERVER_PROPERTIES: "true"
    USE_AIKAR_FLAGS: "true"
    INIT_MEMORY: "3G"
    MAX_MEMORY: "7G"
    ENABLE_AUTOPAUSE: "TRUE"
    AUTOPAUSE_TIMEOUT_INIT: "90"
    AUTOPAUSE_TIMEOUT_KN: "30"
    AUTOPAUSE_TIMEOUT_EST: "60"
    AUTOPAUSE_PERIOD: "15"
    JVM_DD_OPTS: "disable.watchdog:true"

persistence:
  ## minecraft data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: "fast"
  dataDir:
    # Set this to false if you don't care to persist state between restarts.
    enabled: true
    # existingClaim: nil
    size: 5Gi

podAnnotations: {}

deploymentAnnotations: {}
